### PR TITLE
fix class-names starting with space

### PR DESCRIPTION
**Pull request by vkbansal**
This is a quick fix to remove leading space from class names

**Before:**
prism01

**After:**
prism02

### CODE REVIEW

**Comment by LeaVerou** [comment]
Is there any actual problem with these class names besides aesthetics?

**Comment by vkbansal** [comment]
It's just aesthetics. 
I have compulsion for such thing :p

**Comment by LeaVerou** [comment]
Heh, fair enough. However, I have a bigger compulsion with the aesthetics of the code we work with, rather than the generated markup one only sees in the dev toops. Hope u understand!

**Comment by vkbansal** [comment]
No problem :)

**Pull request closed without merging**
