### PR TITLE
Added new C# 5 keywords

### PR DESCRIPTION
**Pull request by XVincentX**
Related issue: #480 
I just added few new keywords introduced into C# 5.0.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks, merged!

Now somebody needs to run gulp and generate the minified version…

**Comment by Golmote** [comment]
> Now somebody needs to run gulp and generate the minified version…

Done.

**Comment by LeaVerou** [comment]
Thanks!

**Comment by vkbansal** [comment]
> Now somebody needs to run gulp and generate the minified version…

@LeaVerou We can setup `travis-ci` to automatically do such things whenever something is pushed and this would also solve #180

**Comment by LeaVerou** [comment]
That would be great, but I’ve never worked with Travis and have no clue how to work with that. Could you describe a bit more how this would work? Thanks!

**Pull request merged**
