### PR TITLE
Added TypeScript definition

### PR DESCRIPTION
**Pull request by vkbansal**
typescript

### CODE REVIEW

**Comment by LeaVerou** [comment]
thanks, merged!

At some point we should convert all keywords to arrays, so we can push and remove keywords when overriding languages instead of having to repeat the whole list for just a few changes… (but that should happen after we optimize arrays)

**Comment by Golmote** [comment]
> At some point we should convert all keywords to arrays, so we can push and remove keywords when overriding languages instead of having to repeat the whole list for just a few changes… (but that should happen after we optimize arrays)

#444 is still pending.

**Comment by Golmote** [comment]
@vkbansal About this grammar definition... why are the `Array` and `Function` constructors considered as keywords but not the other native constructors (`Object`, `Date`, `RegExp`...)?

**Comment by vkbansal** [comment]
@golmote because they are not constructors. They are static types just like string or boolean. It's just how typescript is.

**Comment by Golmote** [comment]
Alright then ^^

**Comment by LeaVerou** [comment]
> #444 is still pending.

Yes, I know, and it’s my fault :(

**Pull request merged**
