### PR TITLE
fixes #464 crlf issue

### LINKED ISSUE #464: Show invisible plugin does not handle windows line endings well
capture2

It's get weirder when combined with line-numbers plugin

### PR DESCRIPTION
**Pull request by vkbansal**
Before:
capture2

After:
capture3

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks, merged!

Which browser did this issue happen in?

**Comment by vkbansal** [comment]
Tested on IE11, Firefox (Stable and Developer Edition), Opera and Chrome on Windows.

**Comment by vkbansal** [comment]
BTW. Can you fix the CSS for `tab` in this plugin. The empty space after the tab symbol is kind of misleading.

**Comment by LeaVerou** [comment]
No, I was asking in which browsers the original bug was present, not in which ones you tested that the fix works.

**Comment by vkbansal** [comment]
The problem was in all 4 of them.

**Pull request merged**
