### PR TITLE
Added Markdown language

### LINKED ISSUE #30: Add a markdown syntax highlighter
I'm working on a project for offline markdown editing, and I'm totally willing to change the highlighting system for prism.

I'm suggesting a code highlighting for markdown. Probably I will end up implementing this one :)

Thanks

### PR DESCRIPTION
**Pull request by Golmote**
Fixes #30 

Not really sure about the use of the aliases that don't make real sense, but I wasn't confident enough to modify the themes...

### CODE REVIEW

**Comment by vkbansal** [comment]
and what about this PR? When will this be merged?

**Comment by Golmote** [comment]
@vkbansal When @LeaVerou will have time to review it.

**Comment by LeaVerou** [comment]
Looks good to me. Conflicts need to be resolved.

However, for MD, it might be a good idea to apply some formatting instead of just highlighting it. E.g. make bold tokens bold, make italic tokens italic, Make headings bigger, de-emphasize the MD symbols to make the content stand out (like Byword does) etc.

**Comment by Golmote** [comment]
@LeaVerou Does it look better now?

prism-markdown

**Comment by LeaVerou** [comment]
Nice!
Btw, we can fix some of the issues by:
- Giving priority to MD over HTML highlighting
- Adding nested rules after we define the grammar, for some common cases

**Comment by Golmote** [comment]
Giving priority to MD over HTML will raise other issues, like the inability to comment markdown:
```markdown
<!-- *italic* -->
```
It will also break HTML highlighting in some cases like this one:
```markdown
<div class="_test_"></div>
```

Are we sure we want to do this?

**Comment by LeaVerou** [comment]
If commenting is the main conflict, we can add it as a separate token. But if cases like the second are common, then probably not a good idea. I’m really not sure :(

**Comment by Golmote** [comment]
I don't think people really make extensive use of HTML attributes in markup. So I guess it's ok to give priority to MD.

**Comment by LeaVerou** [comment]
Then we should probably add a comment token early on, referencing HTML’s comment token.

**Comment by Golmote** [comment]
I inserted markdown before the `prolog` key of markup, so HTML comments have priority.

I added some nested patterns with `inside` but since the bold, italic and link patterns are in competition, the result is not perfect.

prism-markdown

**Comment by mAAdhaTTah** [comment]
Just FYI, looks like some of the edge cases are no longer (italic looks like it's working inside bold).

**Comment by Golmote** [comment]
@mAAdhaTTah Yes, that is why the text says "italic inside bold does work". ^^

**Comment by mAAdhaTTah** [comment]
Reading comprehension FTW. :-p

**Comment by Golmote** [comment]
Is it more clear like this?

prism-markdown

**Comment by mAAdhaTTah** [comment]
Works for me.

**Comment by Golmote** [comment]
@LeaVerou Looks good for you?

**Comment by LeaVerou** [comment]
Sure! It’s not perfect, but then again, what is :)

**Pull request merged**
